In [1]:
import numpy as np

In [18]:
X = np.array([[1,60], [1,50], [1,75]])

In [19]:
X

array([[ 1, 60],
       [ 1, 50],
       [ 1, 75]])

In [20]:
X.T

array([[ 1,  1,  1],
       [60, 50, 75]])

In [21]:
np.dot(X.T, X)

array([[    3,   185],
       [  185, 11725]])

In [22]:
P1 = np.linalg.inv(np.dot(X.T, X))
P1

array([[  1.23421053e+01,  -1.94736842e-01],
       [ -1.94736842e-01,   3.15789474e-03]])

In [23]:
P2 = np.dot(P1, X.T)
P2

array([[ 0.65789474,  2.60526316, -2.26315789],
       [-0.00526316, -0.03684211,  0.04210526]])

In [24]:
y = np.array([10, 7, 12])
y

array([10,  7, 12])

In [25]:
np.dot(P2, y)

array([-2.34210526,  0.19473684])